### ISSUE TITLE
Menu link options > Menu name not working?

### ISSUE THREAD

**Issue by pe7er** [joomla-projects/gsoc16_menu-for-article#20]
#### Steps to reproduce the issue

Discover + install + publish the "Content - Createmenulink" plugin.
Create a new article. 
On [Menu link options] the default value for the field "Menu name" is "About Joomla".
Select another one, e.g. "Main menu"
Save
#### Expected result

I would expect that [Menu link options] would show "Main menu" as menu name.
And that a new menu item would have been created in the menu Main menu.
#### Actual result

[Menu link options] shows "About Joomla" as menu name,
and no menu items seems to have been created.

**Comment by shubhamnba2009** [comment]
Hi @pe7er 
I tried with a fresh install on a new staging Joomla-CMS

I would like to highlight some points.
1. In order to have [Content-createmenulink] plugin working you have to copy from this folder: https://github.com/shubhamnba2009/gsoc16_menu-for-article/tree/menuplugin/media/plg_content_createmenulink to this folder in your local machine path-to-joomla-folder/media/plg_content_createmenulink
1. Also make sure you have copy pasted languages file from administrator/language/en-GB to your local machine.
2. Then try to discover->install->publish the plugin

I tried with fresh install of joomla cms and plugin and was not able to reproduce the error specified by you. Tell me if above solution solves the issue said by you.

**Comment by pe7er** [comment]
I've copied the two JS files from your other repo to my local /media/ folder as you suggested.

I got an error message "Notice: Undefined index: menuordering in /home/username/www/gsoc/gsoc16_menu-for-article/plugins/content/createmenulink/createmenulink.php on line 195" because
administrator/components/com_menus/models/item.php has currently in PR #15 
require_once JPATH_COMPONENT . '/helpers/menus.php';
See: https://github.com/joomla-projects/gsoc16_menu-for-article/pull/15/files

When I change it back to 
JLoader::register('MenusHelper', JPATH_ADMINISTRATOR . '/components/com_menus/helpers/menus.php');
it is working correctly.

**Comment by pe7er** [comment]
Thanks, working ok now
